const ERROR_CODES = {
  // Auth
  AUTH_INVALID_CREDENTIALS: "AUTH_001",
  AUTH_TOKEN_MISSING: "AUTH_002",
  AUTH_TOKEN_INVALID: "AUTH_003",
  AUTH_TOKEN_EXPIRED: "AUTH_004",
  AUTH_FORBIDDEN: "AUTH_005",

  // Validation
  VALIDATION_ERROR: "VAL_001",

  // Resource
  NOT_FOUND: "RES_001",
  CONFLICT: "RES_002",

  // Request
  REQUEST_INVALID_STATUS: "REQ_001",
  REQUEST_NOT_FOUND: "REQ_002",

  // Work Item
  WORK_ITEM_NOT_FOUND: "WI_001",
  WORK_ITEM_WRONG_OWNER: "WI_002",

  // Server
  SERVER_ERROR: "SRV_001",
};

module.exports = ERROR_CODES;
